### ISSUE TITLE
don't use async and callback together

### ISSUE THREAD

**Issue by sw-yx** [verygoodsecurity/netlify-addon-demo#1]
https://github.com/verygoodsecurity/netlify-addon-demo/blob/b1c448ba504f651141ffb02645bd68a599527095/fn/stripe.js#L52

this causes unpredicatble errors. instead, just pick one or the other. see this https://serverless.com/blog/common-node8-mistakes-in-lambda/#still-using-callbacks

**Comment by ilovetea** [comment]
done
